name: cotacao_direta
description: Um aplicativo simples que mostra a cotação das principais moedas frente ao real
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

enable-experiment:
  - extension-methods

dependencies:
  flutter:
    sdk: flutter
  sprintf: ^6.0.0
  http: ^0.13.3
  intl: ^0.17.0
  xml: ^5.3.0
  mobx: ^2.0.4
  charts_flutter: ^0.11.0
  sqflite: ^2.0.0+4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
  assets:
    - assets/secrets/secrets.json