name: cotacao_direta
description: Um aplicativo simples que mostra a cotação das principais moedas frente ao real
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

enable-experiment:
  - extension-methods

dependencies:
  flutter:
    sdk: flutter
  sprintf: ^7.0.0
  http: 1.2.0
  intl: 0.18.1
  # flutter 1.22 not supported by this lib
  #  flutter_stetho: ^0.6.0-dev.1
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  sqflite: 2.3.2
  path: 1.8.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf