name: cotacao_direta
description: Um aplicativo simples que mostra a cotação das principais moedas frente ao real
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  sprintf: "^4.0.2"
  http: 0.12.1
  intl: 0.16.1
  flutter_stetho: ^0.5.2
  cupertino_icons: ^0.1.3
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  sqflite: 1.3.1
  path: 1.7.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.5"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf